# Generated by Django 5.1.4 on 2024-12-15 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="vote", name="candidate",),
        migrations.RemoveField(model_name="vote", name="timestamp",),
        migrations.RemoveField(model_name="vote", name="voter",),
        migrations.AddField(
            model_name="election",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="election",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="voting.election",
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vote", name="voted", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="election", name="name", field=models.CharField(max_length=100),
        ),
    ]
