# Generated by Django 5.1.4 on 2024-12-15 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0002_remove_vote_candidate_remove_vote_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="voting.candidate",
            ),
        ),
    ]
